plugins {
    id 'org.springframework.boot' version '2.6.7'

    // https://plugins.gradle.org/search?term=com.github.node-gradle.node
    id "com.github.node-gradle.node" version "3.2.1"

    // https://plugins.gradle.org/search?term=com.google.cloud.tools.jib
    id "com.google.cloud.tools.jib" version "3.1.4"
}

apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'

version = '0.5.5'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }

    archivesBaseName = 'spring-boot-kisses-angular'
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
}

def generatedResources = "src/generated/resources"

sourceSets {
    main {
        output.dir(generatedResources, builtBy: 'ngBuild')
    }
}

node {
    // https://nodejs.org/en/about/releases/
    version = '14.19.1'
    download = true
}

task npmAudit(type: NpmTask, dependsOn: 'npmInstall') {
    args = ['audit']
}

task npmAuditFix(type: NpmTask, dependsOn: 'npmInstall') {
    args = ['audit', 'fix']
}

task ngBuild(type: NpxTask, dependsOn: 'npmInstall') {
    command = '@angular/cli@13.3.3'
    args = ['build', '--configuration', 'production']
}

task ngServeProduction(type: NpxTask, dependsOn: 'ngBuild') {
    command = '@angular/cli@13.3.3'
    args = ['serve', '--open', '--configuration=production' ]
}

task ngUpdate(type: NodeTask, dependsOn: 'npmInstall') {
    script = project.file('node_modules/@angular/cli/bin/ng')
    args = ['update']
}

processResources.dependsOn 'ngBuild'

jibDockerBuild.dependsOn 'processResources'

jib {
    to {
        image = 'datenkollektiv/spring-boot-kisses-angular'
        tags = ['latest', project.version] as List<String>
    }
    container {
        appRoot = '/app'
        ports = ['8080']
        workingDirectory = '/app'
    }
    extraDirectories {
        paths {
            path {
                from = file(generatedResources)
                into = '/app'
            }
        }
    }
}

clean.delete << file('node_modules')
clean.delete << file(generatedResources)
